### ISSUE TITLE
OTS parsing error: head: Failed to parse table

### ISSUE THREAD

**Issue by evandiamond** [inwardmovement/test-icons-to-font#1]
The console error gave me something to go by. The fonts weren't loading because of this error:
```
OTS parsing error: head: Failed to parse table
```

So, something was corrupted.

I removed all your icons, added one from mine that I know works, ran `npm run svg` and `npm run font` and it compiled fine. 

I ran it again with two icons. One of mine and one of yours and it broke the fonts.

I noticed your icons had defined width and height with an `em` which I thought was odd... 

Example:
`width="1em" height="1em"`

If you remove it and re-run the commands it all works! So you can add another plugin flag to do it automatically with svgmin.

```
const {src, dest, series} = require('gulp'),
    svgmin = require('gulp-svgmin');

function svg() {
    return src('icons/*.svg')
        .pipe(svgmin({
            plugins: [
                {
                    removeDimensions: true
                }, {
                    mergePaths: {
                        noSpaceAfterFlags: false
                    }
                }, {
                    convertPathData: {
                        noSpaceAfterFlags: false
                    }
                }]
        }))
        .pipe(dest('svgo'))
}

exports.svg = series(svg);
```

Hopefully the above info helps! Good luck!

**Comment by inwardmovement** [comment]
The icons are rendered but not properly, I'll have to tweak the parameters of SVGO... thanks!
